# Generated by Django 5.1.1 on 2025-12-06 16:47

import django.db.models.deletion
import education.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_remove_academic_year_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Transcript Template', help_text='Template name', max_length=200)),
                ('template_file', models.FileField(help_text='Upload PDF or image template (PNG, JPG)', upload_to=education.models.transcript_template_upload_path)),
                ('template_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image (PNG/JPG)')], default='pdf', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active template per college')),
                ('field_positions', models.JSONField(blank=True, default=dict, help_text='Field positions and styling (JSON)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_templates', to='education.college')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_transcript_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transcript_templates',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['college', 'is_active'], name='transcript__college_aa2e4a_idx')],
            },
        ),
    ]
