# Generated by Django 5.1.1 on 2025-12-30 05:54

import education.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_add_transcript_template_margins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcripttemplate',
            name='template_file',
            field=models.FileField(help_text='Upload PDF template (PDF templates only - no image conversion)', upload_to=education.models.transcript_template_upload_path),
        ),
        migrations.AlterField(
            model_name='transcripttemplate',
            name='template_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image (PNG/JPG) - Deprecated')], default='pdf', help_text='Note: Only PDF templates are supported. Image templates are deprecated.', max_length=10),
        ),
    ]
