# Generated by Django 5.1.1 on 2026-01-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0029_add_department_to_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(help_text='Date of check-in')),
                ('check_in_time', models.DateTimeField(help_text='Date and time when staff signed in')),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Date and time when staff signed out', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_checkins', to='education.college')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['lecturer', 'principal', 'registrar', 'accounts_officer', 'reception']}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_daily_checkins',
                'ordering': ['-check_in_date', '-check_in_time'],
                'indexes': [models.Index(fields=['staff', 'check_in_date'], name='staff_daily_staff_i_32a66c_idx'), models.Index(fields=['college', 'check_in_date'], name='staff_daily_college_9b6610_idx'), models.Index(fields=['check_in_date'], name='staff_daily_check_i_a3bc26_idx'), models.Index(fields=['staff', 'check_in_time'], name='staff_daily_staff_i_a16d48_idx')],
                'unique_together': {('staff', 'check_in_date')},
            },
        ),
    ]
